apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
          app: python
    spec:
      containers:
        - name: python-app
          image: princysearce/python-app:v2
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 300Mi
          ports:
          - name: python-port
            containerPort: 5000

